# Generated by Django 5.2.9 on 2026-01-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables - Leafy', 'Vegetables - Leafy'), ('Vegetables - Root', 'Vegetables - Root'), ('Vegetables - Marrow', 'Vegetables - Marrow'), ('Fruits - Seasonal', 'Fruits - Seasonal'), ('Fruits - Tropical', 'Fruits - Tropical'), ('Fruits - Berries', 'Fruits - Berries'), ('Grains & Cereals - Rice', 'Grains & Cereals - Rice'), ('Grains & Cereals - Wheat', 'Grains & Cereals - Wheat'), ('Grains & Cereals - Corn', 'Grains & Cereals - Corn'), ('Pulses & Legumes - Lentils', 'Pulses & Legumes - Lentils'), ('Pulses & Legumes - Beans', 'Pulses & Legumes - Beans'), ('Pulses & Legumes - Peas', 'Pulses & Legumes - Peas'), ('Dairy Products - Milk', 'Dairy Products - Milk'), ('Dairy Products - Butter', 'Dairy Products - Butter'), ('Dairy Products - Cheese', 'Dairy Products - Cheese'), ('Livestock - Poultry', 'Livestock - Poultry'), ('Livestock - Cattle', 'Livestock - Cattle'), ('Livestock - Sheep', 'Livestock - Sheep'), ('Spices & Herbs', 'Spices & Herbs')], max_length=50),
        ),
    ]
